[package]
name = "grammarsize"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-cors = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
neo4rs = "0.8.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"