name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run fmt
        run: cargo fmt --all --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test

  frontend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format Check
        run: npm run format:check
